// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;

using BlahguaMobile.BlahguaCore;

using Foundation;
using UIKit;
using MonoTouch.Dialog.Utilities;



namespace BlahguaMobile.IOS
{
	public class BGHistoryTableSource : UITableViewSource
	{
		private BGHistoryViewController vc;

		public BGHistoryTableSource(BGHistoryViewController vc) : base()
		{
			this.vc = vc;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = (BGHistoryTableCell)tableView.DequeueReusableCell ("historyCell");
			if(indexPath.Row == 0)
			{
				int count = vc.UserBlahs == null ? 0 : vc.UserBlahs.Count;
				cell.SetUp ("Posts", count.ToString());
			}
			else
			{
				int count = vc.UserComments == null ? 0 : vc.UserComments.Count;
				cell.SetUp ("Comments", count.ToString());
			}
			return cell;
		}

		public override nfloat GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
		{
			return 64f;
		}

		public override nint NumberOfSections (UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection (UITableView tableview, nint section)
		{
			return 2;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			if(indexPath.Row == 0) {
				int count = vc.UserBlahs == null ? 0 : vc.UserBlahs.Count;
				if (count > 0) {

					vc.SetMode (false, true); 
					vc.PerformSegue ("fromHistoryToDetail",vc);
				}

			}
			else
			{
				int count = vc.UserComments == null ? 0 : vc.UserComments.Count;
				if (count > 0) {

					vc.SetMode (true, false);
					vc.PerformSegue ("fromHistoryToDetail",vc);

				}

			}

	   }
	}

}
