// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public enum BGLeftMenuType
	{
		Channels
	}

	public partial class BGLeftMenuTableViewController : UITableViewController
	{

		private BGSlidingMenuTableSource channelsTypesTableSource = new BGSlidingMenuTableSource (BGLeftMenuType.Channels);


		public BGLeftMenuTableViewController (IntPtr handle) : base (handle)
		{
		}

		public BGLeftMenuTableViewController() : base()
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

            View.BackgroundColor = UIColor.FromPatternImage (UIImage.FromBundle ("darkGrayBack"));
			BlahguaCore.BlahguaAPIObject.Current.PropertyChanged += (object sender, PropertyChangedEventArgs e) => 
			{

				if(e.PropertyName == "CurrentChannelList")
				{
					TableView.ReloadData();
				}
			};
			SwitchTableSource (BGLeftMenuType.Channels);
			TableView.TableFooterView = new UIView ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			TableView.ReloadData ();
		}

		public void SwitchTableSource(BGLeftMenuType type)
		{
			TableView.DeselectRow (TableView.IndexPathForSelectedRow, false);
            if (type == BGLeftMenuType.Channels) {
                View.Hidden = false;
                TableView.Source = channelsTypesTableSource;
			} 
			else
			{
                View.Hidden = true;
                TableView.Source = null;
			}

			TableView.ReloadData ();


		}
	}

}