// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGMainNavigationController : UINavigationController
	{
		public BGMainNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
