// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGNewCommentViewController : UIViewController
	{
		public BGNewCommentViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
