// This file has been autogenerated from a class added in the UI designer.

using System;
using System.ComponentModel;

using BlahguaMobile.BlahguaCore;

using MonoTouch.SlideMenu;
using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGRollViewController : UICollectionViewController
	{
		#region Fields

		private SlideMenuController leftSlidingPanel;
		private BGRollViewCellsSizeManager manager;

		#endregion

		#region Properties
		#endregion

		public BGRollViewController (IntPtr handle) : base (handle)
		{
		}

		#region View Controller Overriden Methods

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			CollectionView.BackgroundColor = UIColor.FromPatternImage (UIImage.FromFile ("grayBack.png"));

			leftSlidingPanel = ((AppDelegate)UIApplication.SharedApplication.Delegate).SlideMenu;

			NavigationItem.LeftBarButtonItem = new UIBarButtonItem (UIImage.FromFile("leftMenuButton.png"), UIBarButtonItemStyle.Plain, MenuButtonClicked);
			if(BlahguaCore.BlahguaAPIObject.Current.CurrentUser == null)
			{
				NavigationItem.RightBarButtonItem = new UIBarButtonItem ("Log in", UIBarButtonItemStyle.Plain, LoginButtonClicked);
			}
			else
			{
				NavigationItem.RightBarButtonItem = new UIBarButtonItem ("Ok", UIBarButtonItemStyle.Plain, LoginButtonClicked);
			}

			BlahguaCore.BlahguaAPIObject.Current.PropertyChanged += (object sender, PropertyChangedEventArgs e) => 
			{
				if(e.PropertyName == "CurrentChannel")
				{
					CollectionView.ScrollToItem(NSIndexPath.FromItemSection(0, 0), UICollectionViewScrollPosition.Top, true);
					((BGRollViewDataSource)CollectionView.DataSource).DataSource.Clear();
					BlahguaAPIObject.Current.GetInbox (InboxLoadingCompleted);
				}
			};

			manager = new BGRollViewCellsSizeManager ();
			BlahguaAPIObject.Current.GetInbox (InitialInboxLoadingCompleted);
		}

		#endregion

		#region Methods

		public void RefreshData()
		{
			BlahguaAPIObject.Current.GetInbox (InboxLoadingCompleted);
		}

		private void MenuButtonClicked(object sender, EventArgs args)
		{
			leftSlidingPanel.ToggleMenuAnimated ();
		}

		private void LoginButtonClicked(object sender, EventArgs args)
		{

		}

		private void InitialInboxLoadingCompleted (Inbox theList)
		{
			InvokeOnMainThread (() => {
				CollectionView.DataSource = new BGRollViewDataSource (manager, this);
				CollectionView.CollectionViewLayout = new BGRollViewLayout (manager, this);
				CollectionView.Delegate = new BGRollViewLayoutDelegate (manager);
				InboxLoadingCompleted (theList);
			});
		}
			
		private void InboxLoadingCompleted(Inbox inbox)
		{
			InvokeOnMainThread (() => {
				inbox.PrepareBlahs ();
				((BGRollViewDataSource)CollectionView.DataSource).InboxBlahs.AddRange(inbox);
				CollectionView.ReloadData ();
			});
		}

		#endregion
	}
}
