// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Linq.Expressions;

using BlahguaMobile.BlahguaCore;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGSignaturesTableViewController : UITableViewController
	{
		public BGSignaturesTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			TableView.TableFooterView = new UIView ();
			TableView.Source = new BGSignaturesTableSource ();
		}


		public class BGSignaturesTableSource : UITableViewSource
		{
			#region implemented abstract members of UITableViewSource

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				var cell = (BGSignaturesCell)tableView.DequeueReusableCell ("cell");
				if(indexPath.Row == 0)
				{
					cell.SetUp ("User Profile");
				}
				else
				{
					if (BlahguaAPIObject.Current.CurrentUser.Badges != null && BlahguaAPIObject.Current.CurrentUser.Badges.Any ())
						cell.SetUp (BlahguaAPIObject.Current.CurrentUser.Badges [indexPath.Row + 1].BadgeName);
				}
				return cell;
			}

			public override int RowsInSection (UITableView tableview, int section)
			{
				int count = 1;
				if(BlahguaAPIObject.Current.CurrentUser.Badges != null && BlahguaAPIObject.Current.CurrentUser.Badges.Any())
				{
					count += BlahguaAPIObject.Current.CurrentUser.Badges.Count;
				}
				return count;
			}

			public override int NumberOfSections (UITableView tableView)
			{
				return 1;
			}

			public override float GetHeightForRow (UITableView tableView, NSIndexPath indexPath)
			{
				if(indexPath.Row == 0)
				{
					return 36f;
				}
				else
				{
					return 28f;
				}
			}

			#endregion


		}
	}
}
