// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;

using BlahguaMobile.BlahguaCore;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGStatsTableViewController : UITableViewController
	{
		private UIViewController parentViewController;

		private Blah CurrentBlah
		{
			get
			{
				return BlahguaAPIObject.Current.CurrentBlah;
			}
		}

		public BGStatsTableViewController (IntPtr handle) : base (handle)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			Dictionary<string, string> source = new Dictionary<string, string> ();
			if(CurrentBlah != null)
			{
				source.Add ("Opened: ", CurrentBlah.O.ToString ());
				source.Add ("Viewed: ", CurrentBlah.V.ToString ());
				source.Add ("Promotes: ", CurrentBlah.P.ToString ());
				source.Add ("Demotes: ", CurrentBlah.D.ToString ());
				source.Add ("Comments: ", CurrentBlah.C.ToString ());
			}
			TableView.Source = new BGStatsTableSource (source);
		}

		public void SetParentViewController (UIViewController parentViewController)
		{
			this.parentViewController = parentViewController;
		}
	}

	public class BGStatsTableSource : UITableViewSource
	{
		private Dictionary<string, string> source;

		public BGStatsTableSource(Dictionary<string, string> source) : base()
		{
			this.source = source;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			var cell = (BGStatsTableCell)tableView.DequeueReusableCell ("cell");
			var element = source.ElementAt (indexPath.Row);
			cell.SetKeyValue (element.Key, element.Value);
			return cell;
		}

		public override int RowsInSection (UITableView tableview, int section)
		{
			return source.Count;
		}

		public override int NumberOfSections (UITableView tableView)
		{
			return 1;
		}
	}
}
