// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MonoTouch.Dialog.Utilities;
using SDWebImage;

namespace BlahguaMobile.IOS
{
	public partial class BGBadgeCell : UICollectionViewCell
	{
		public BGBadgeCell (IntPtr handle) : base (handle)
		{
		}

		public void SetUp(string imageUrl, string text)
		{
			name.AttributedText = new NSAttributedString (text, UIFont.FromName (BGAppearanceConstants.FontName, 15), UIColor.Black);
			badgeImage.SetImage(new NSUrl(imageUrl));
		}



	}
}
