// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog.Utilities;

namespace BlahguaMobile.IOS
{
	public partial class BGBadgeCell : UICollectionViewCell
	{
		public BGBadgeCell (IntPtr handle) : base (handle)
		{
		}

		public void SetUp(string imageUrl, string text)
		{
			name.AttributedText = new NSAttributedString (text, UIFont.FromName (BGAppearanceConstants.FontName, 17), UIColor.Black);
			badgeImage.Image = ImageLoader.DefaultRequestImage (new Uri (imageUrl), new ImageUpdateDelegate (badgeImage));
		}
	}
}
