// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MonoTouch.Dialog.Utilities;
using BlahguaMobile.BlahguaCore;
using SDWebImage;

namespace BlahguaMobile.IOS
{
	public partial class BGBlahBadgeCell : UITableViewCell
	{
		public BGBlahBadgeCell (IntPtr handle) : base (handle)
		{
		}

        public void SetUp(BadgeRecord theBadge)
        {
			verifiedLabel.AttributedText = new NSAttributedString (
				"verified", 
				UIFont.FromName (BGAppearanceConstants.MediumFontName, 10), 
				UIColor.Black
			);
			Uri uri = null;
			if (Uri.TryCreate (theBadge.URL, UriKind.RelativeOrAbsolute, out uri)) {
				badgeImage.SetImage(new NSUrl(uri.ToString()), UIImage.FromBundle("badges"), 
				                    (image, error, cacheType, imageUrl) =>
				{

				});
			} else
				badgeImage.Image = UIImage.FromBundle ("badges");

			DecorateBadge(theBadge.N);
        }

        private void DecorateBadge (string badgeNameStr)
        {
            this.badgeName.AttributedText = new NSAttributedString (
                badgeNameStr, 
                UIFont.FromName (BGAppearanceConstants.BoldFontName, 10), 
                UIColor.Black
            );
        }
			
	}
}
