// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;

using BlahguaMobile.BlahguaCore;

using Foundation;
using UIKit;
using MonoTouch.Dialog.Utilities;

namespace BlahguaMobile.IOS
{
	public partial class BGCommentTableCell : UITableViewCell, IImageUpdated
    {
        private UIPanGestureRecognizer panRecognizer;
		private UITapGestureRecognizer tapRecognizer;
		private UITapGestureRecognizer imageTapRecognizer;

        private CGPoint panStartPoint;
        private nfloat startingLayoutRight = 0;
        private Comment userComment;
		private UITableView parentTableView;

        public BGCommentTableCell(IntPtr handle)
            : base(handle)
        {
        }

        private class BGCommentBadgesTableSource : UITableViewSource
        {
            private Comment linkedComment;

            public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
            {
                var cell = (BGBlahBadgeCell)tableView.DequeueReusableCell("cell");
                cell.SetUp(linkedComment.Badges[indexPath.Row]);
                return cell;
            }

            public Comment LinkedComment
            {
                get { return linkedComment; }
                set
                {
                    linkedComment = value;
                    if (linkedComment.Badges != null)
                    {
                        foreach (BadgeReference curBadge in linkedComment.Badges)
                        {
                            curBadge.UpdateBadge();
                        }
                    }
                }
            }

            public override nint RowsInSection(UITableView tableview, nint section)
            {
                if ((linkedComment != null) && (linkedComment.BD != null))
                    return linkedComment.BD.Count;
                else
                    return 0;
            }

            public override nint NumberOfSections(UITableView tableView)
            {
                return 1;
            }


        }

		public void SetUp(Comment theComment, UITableView tableView)
        {
            string userId = "0";  // signed out user
            if (BlahguaAPIObject.Current.CurrentUser != null)
                userId = BlahguaAPIObject.Current.CurrentUser._id;
            this.userComment = theComment;
            bool isUserBlah = userId.Equals(BlahguaAPIObject.Current.CurrentBlah.A);
            bool isUserComment = userId.Equals(userComment.A);

			parentTableView = tableView;
            panRecognizer = new UIPanGestureRecognizer(PanThisCell);
            panRecognizer.Delegate = new PanGestureRecognizerDelegate();
            containerView.TranslatesAutoresizingMaskIntoConstraints = false;
            //containerView.AddGestureRecognizer(panRecognizer);

			Action action = () => {
                UIView.BeginAnimations ("AnimateForVote");
                UIView.SetAnimationBeginsFromCurrentState (true);
                UIView.SetAnimationDuration(.25);
                UIView.SetAnimationCurve(UIViewAnimationCurve.EaseIn);
				if (rightPosition.Constant == voteView.Frame.Width) {
					rightPosition.Constant = 0;
				} else {
					rightPosition.Constant = voteView.Frame.Width;
				}
                UIView.CommitAnimations();
			};

            if (BlahguaAPIObject.Current.CurrentUser != null)
            {
                tapRecognizer = new UITapGestureRecognizer(action);

                tapRecognizer.Delegate = new PanGestureRecognizerDelegate();

                tapRecognizer.NumberOfTapsRequired = 1;
                containerView.AddGestureRecognizer(tapRecognizer);
            }

            containerView.TranslatesAutoresizingMaskIntoConstraints = false;

			Action showFullScreen = () => {
				if(commentImageView.Image != null)
				{
					var myStoryboard = ((AppDelegate)UIApplication.SharedApplication.Delegate).MainStoryboard;
					FullScreenView fs = new FullScreenView(commentImageView.Image);
					((AppDelegate)UIApplication.SharedApplication.Delegate).swipeView.NavigationController.PushViewController(fs,false);
				}

			};

			imageTapRecognizer = new UITapGestureRecognizer (showFullScreen);
			imageTapRecognizer.Delegate = new PanGestureRecognizerDelegate ();
			containerView.TranslatesAutoresizingMaskIntoConstraints = false;
			imageTapRecognizer.NumberOfTapsRequired = 1;
			commentImageView.AddGestureRecognizer (imageTapRecognizer);

            BGCommentBadgesTableSource newSource = new BGCommentBadgesTableSource();
            newSource.LinkedComment = userComment;
            badgeTable.Source = newSource;

            if ((userComment.BD != null) && (userComment.BD.Count > 0))
            {
				badgeTable.Hidden = false;
				userComment.AwaitBadgeData ((didIt) => {
					int count = userComment.Badges.Count;
					badgeTableHeight.Constant = count * 28;
					badgeTable.ReloadData();
				});
                
            }
            else
            {
				badgeTableHeight.Constant = 0;
                badgeTable.Hidden = true;
            }

            if (!String.IsNullOrEmpty(userComment.AuthorImage))
			{
                imgAvatar.Image = ImageLoader.DefaultRequestImage(new Uri(userComment.AuthorImage), new ImageUpdateDelegate(imgAvatar));
			}

            if (!String.IsNullOrEmpty(userComment.ImageURL))
            {
				try {
					commentImageView.LayoutIfNeeded ();
					commentImageView.Image = ImageLoader.DefaultRequestImage(new Uri(userComment.ImageURL), this);

					if (commentImageView.Image != null) {
						UIImage img = commentImageView.Image;
						imageViewHeight.Constant = img.Size.Height / img.Size.Width * commentImageView.Frame.Width;
					} else
						imageViewHeight.Constant = 0;
				}
				catch (Exception exp) {
					System.Console.WriteLine (exp.Message);
					imageViewHeight.Constant = 0;
				}
            }
            else
            {
                commentImageView.Image = null;
                imageViewHeight.Constant = 0;
            }

            if (!String.IsNullOrEmpty(userComment.T))
            {
                text.AttributedText = new NSAttributedString(userComment.T, UIFont.FromName(BGAppearanceConstants.FontName, 14), UIColor.Black);
                text.ScrollEnabled = false;
            }

			lblUserType.AttributedText = new NSAttributedString(
                userComment.DescriptionString,
				UIFont.FromName(BGAppearanceConstants.MediumItalicFontName, 12),
				UIColor.Black
			);

            author.AttributedText = new NSAttributedString(
                userComment.AuthorName,
                UIFont.FromName(BGAppearanceConstants.MediumFontName, 16),
				BGAppearanceConstants.TealGreen
            );

            string timeAgo= Utilities.ElapsedDateString(userComment.CreationDate);

            timespan.AttributedText = new NSAttributedString(
				timeAgo,
                UIFont.FromName(BGAppearanceConstants.MediumFontName, 12),
                UIColor.Black
            );

            upAndDownVotes.AttributedText = new NSAttributedString(
                userComment.UpVoteCount.ToString() + "/" + userComment.DownVoteCount.ToString(),
                UIFont.FromName(BGAppearanceConstants.MediumFontName, 16),
                UIColor.Black
            );

            voteView.BackgroundColor = BGAppearanceConstants.TealGreen;

            if (isUserBlah || isUserComment)
            {
                downVoteButton.SetImage(UIImage.FromFile("arrow_down.png"), UIControlState.Normal);
                upVoteButton.SetImage(UIImage.FromFile("arrow_up.png"), UIControlState.Normal);
                upVoteButton.Enabled = false;
                downVoteButton.Enabled = false;
            }
            else
            {
                if (userComment.uv == -1)
                {
                    downVoteButton.SetImage(UIImage.FromFile("arrow_down_dark.png"), UIControlState.Normal);
                    upVoteButton.SetImage(UIImage.FromFile("arrow_up.png"), UIControlState.Normal);
                    upVoteButton.Enabled = false;
                    downVoteButton.Enabled = false;
                }
                else if (userComment.uv == 1)
                {
                    downVoteButton.SetImage(UIImage.FromFile("arrow_down.png"), UIControlState.Normal);
                    upVoteButton.SetImage(UIImage.FromFile("arrow_up_dark.png"), UIControlState.Normal);
                    upVoteButton.Enabled = false;
                    downVoteButton.Enabled = false;
                }
                else
                {
                    upVoteButton.Enabled = true;
                    downVoteButton.Enabled = true;
                }
            }
            
                
            downVoteButton.TouchUpInside += (sender, e) =>
                {
                    SetCommentVote(-1);
                };

            upVoteButton.TouchUpInside += (sender, e) =>
                {
                    SetCommentVote(1);
                };
        }

        private void SetCommentVote(int theVote)
        {
            if((BlahguaAPIObject.Current.CurrentUser != null) && 
                (userComment.uv != -1) && 
                (userComment.uv != 1))
            {
                BlahguaAPIObject.Current.SetCommentVote(userComment, theVote, (v) =>
                    {
                        if (v != theVote)
                        {
                            // something happend
                        }
                        else if (v != userComment.uv)
                        {
                            userComment.uv = v;
                            InvokeOnMainThread( () => 
                                {
                                    if (v == 1)
                                    {
                                        downVoteButton.SetImage(UIImage.FromFile("arrow_down.png"), UIControlState.Normal);
                                        upVoteButton.SetImage(UIImage.FromFile("arrow_up_dark.png"), UIControlState.Normal);
                                        userComment.UpVoteCount++;
                                    }
                                    else
                                    {
                                        downVoteButton.SetImage(UIImage.FromFile("arrow_down_dark.png"), UIControlState.Normal);
                                        upVoteButton.SetImage(UIImage.FromFile("arrow_up.png"), UIControlState.Normal);
                                        userComment.DownVoteCount++;
                                    }
                                    upVoteButton.Enabled = false;
                                    downVoteButton.Enabled = false;

                                    upAndDownVotes.AttributedText = new NSAttributedString(
                                        userComment.UpVoteCount.ToString() + "/" + userComment.DownVoteCount.ToString(),
                                        UIFont.FromName(BGAppearanceConstants.BoldFontName, 14),
                                        UIColor.Black);
                                    rightPosition.Constant = 0;
                                });
                        }
                    });
            }
        }

		#region IImageUpdated implementation

		public void UpdatedImage(Uri uri)
		{
			commentImageView.Image = ImageLoader.DefaultRequestImage(uri, this);
			if (commentImageView.Image != null) {
				UIImage img = commentImageView.Image;
				nfloat newHeight = img.Size.Height / img.Size.Width * commentImageView.Frame.Width;


				imageViewHeight.Constant = newHeight;
				//containerViewHeight.Constant = containerViewHeight.Constant + newHeight;
				//SetNeedsUpdateConstraints();
				parentTableView.ReloadData ();
			}

		}

		#endregion

        public void PanThisCell(UIPanGestureRecognizer recognizer)
        {
            switch (recognizer.State)
            {
                case UIGestureRecognizerState.Began:
                    panStartPoint = recognizer.TranslationInView(containerView);
                    break;
                case UIGestureRecognizerState.Changed:
                    CGPoint currentPoint = recognizer.TranslationInView(containerView);
                    nfloat deltaX = currentPoint.X - panStartPoint.X;
                    bool panningLeft = false;
                    if (currentPoint.X < panStartPoint.X)
                    {
                        panningLeft = true;
                    }

                    if (startingLayoutRight == 0)
                    {
                        if (!panningLeft)
                        {
                            nfloat constant = (nfloat)Math.Max(-deltaX, 0);
                            if (constant == 0)
                            {
                                ResetToStartPosition(true);
                            }
                            else
                            {
                                rightPosition.Constant = constant;
                            }
                        }
                        else
                        {
                            nfloat constant = (nfloat)Math.Min(-deltaX, ButtonTotalWidth());
                            if (constant == ButtonTotalWidth())
                            {
                                SetFinalContainerViewPosition(true);
                            }
                            else
                            {
                                rightPosition.Constant = constant;
                            }
                        }
                    }
                    else
                    {
                        nfloat adjustment = startingLayoutRight - deltaX;
                        if (!panningLeft)
                        {
                            nfloat constant = (nfloat)Math.Max(adjustment, 0);
                            if (constant == 0)
                            {
                                ResetToStartPosition(true);
                            }
                            else
                            {
                                rightPosition.Constant = constant;
                            }
                        }
                        else
                        {
                            nfloat constant = (nfloat)Math.Min(adjustment, ButtonTotalWidth());
                            if (constant == ButtonTotalWidth())
                            {
                                SetFinalContainerViewPosition(true);
                            }
                            else
                            {
                                rightPosition.Constant = constant;
                            }
                        }
                    }
                    break;
                case UIGestureRecognizerState.Ended:
                    if (startingLayoutRight == 0)
                    {
                        nfloat position = ButtonTotalWidth() / 2 - 1;
                        if (rightPosition.Constant >= position)
                        {
                            SetFinalContainerViewPosition(true);
                        }
                        else
                        {
                            ResetToStartPosition(true);
                        }
                    }
                    else
                    {
                        nfloat position = ButtonTotalWidth() / 2;
                        if (rightPosition.Constant >= position)
                        {
                            SetFinalContainerViewPosition(true);
                        }
                        else
                        {
                            ResetToStartPosition(true);
                        }
                    }
                    break;
                case UIGestureRecognizerState.Cancelled:
                    if (startingLayoutRight == 0)
                    {
                        ResetToStartPosition(true);
                    }
                    else
                    {
                        SetFinalContainerViewPosition(true);
                    }
                    break;
                default:
                    break;
            }
        }

        public void ResetToStartPosition(bool animated)
        {
            if (startingLayoutRight == 0 &&
             rightPosition.Constant == 0)
            {
                //Already all the way closed, no bounce necessary
                return;
            }

            rightPosition.Constant = 0;

            UpdateConstraintsIfNeeded(animated, () =>
            {
                startingLayoutRight = rightPosition.Constant;
            });
        }

        public void SetFinalContainerViewPosition(bool animated)
        {
            if (startingLayoutRight == ButtonTotalWidth() &&
                rightPosition.Constant == ButtonTotalWidth())
            {
                return;
            }

            rightPosition.Constant = ButtonTotalWidth();

            UpdateConstraintsIfNeeded(animated, () =>
            {
                startingLayoutRight = rightPosition.Constant;
            });
        }

        private void UpdateConstraintsIfNeeded(bool animated, Action completionHandler)
        {
            float duration = 0;
            if (animated)
            {
                duration = 0.1f;
            }

            UIView.Animate(duration, () =>
            {
                LayoutIfNeeded();
            }, completionHandler);
        }

        private nfloat ButtonTotalWidth()
        {
            return voteView.Frame.Width;
        }

        public override void PrepareForReuse()
        {
            base.PrepareForReuse();
            ResetToStartPosition(false);
        }
    }


    public class PanGestureRecognizerDelegate : UIGestureRecognizerDelegate
    {
        public override bool ShouldRecognizeSimultaneously(UIGestureRecognizer gestureRecognizer, UIGestureRecognizer otherGestureRecognizer)
        {
			return false;
        }

        public override bool ShouldReceiveTouch(UIGestureRecognizer recognizer, UITouch touch)
        {
            //			if(touch.View is UIButton)
            //			{
            //				return false;
            //			}
            return true;
        }
    }

}