// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using BlahguaMobile.BlahguaCore;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog.Utilities;

namespace BlahguaMobile.IOS
{
	public partial class BGHistoryDetailCell : UITableViewCell
	{
		private const float baseXStart = 20f;
		private const float space = 8f;

		private SizeF baseSizeForFitting = new SizeF (240, 21);

		private float yCoordStart;
		private float labelXCoordStart;

		public UIImageView commentImageView;

		public BGHistoryDetailCell (IntPtr handle) : base (handle)
		{
		}

		public void SetUp(Blah blah)
		{
			SetUp (blah.ImageURL, blah.T, blah.P.ToString () + "/" + blah.D.ToString ());
		}

		public void SetUp(Comment comment)
		{
			SetUp (comment.ImageURL, comment.T, comment.UpVoteCount.ToString () + "/" + comment.DownVoteCount.ToString ());
		}

		private void SetUp(string imageUrl, string text, string upAndDownVotesText)
		{
			yCoordStart = space;
			labelXCoordStart = baseXStart;
			if(!String.IsNullOrEmpty(imageUrl))
			{
				commentImageView = new UIImageView ();
				commentImageView.Image = ImageLoader.DefaultRequestImage(new Uri(imageUrl), new ImageUpdateDelegate (commentImageView));
				ContentView.AddSubview (commentImageView);
				commentImageView.Frame = new RectangleF (0, yCoordStart, 320f, 161f);
				yCoordStart += commentImageView.Frame.Height + space;
			}

			this.text.RemoveFromSuperview ();
			if(!String.IsNullOrEmpty(text))
			{
				this.text.AttributedText = new NSAttributedString (text, UIFont.FromName (BGAppearanceConstants.FontName, 14), UIColor.Black);

				var newSize = this.text.SizeThatFits (new SizeF (320 - baseXStart * 2, 568));
				ContentView.AddSubview (this.text);
				this.text.Frame = new RectangleF (baseXStart, yCoordStart, 320 - baseXStart * 2, newSize.Height);
				yCoordStart += this.text.Frame.Height + space;
			}

			upAndDownVotes.AttributedText = new NSAttributedString (
				upAndDownVotesText,
				UIFont.FromName (BGAppearanceConstants.BoldFontName, 14), 
				UIColor.Black
			);
			SetLabelSize (upAndDownVotes);


			ContentView.Frame = new RectangleF (0, 0, 320, yCoordStart + upAndDownVotes.Frame.Height + space);
		}

		private void SetLabelSize(UILabel label)
		{
			label.RemoveFromSuperview ();
			var newSize = label.SizeThatFits(baseSizeForFitting);

			label.Frame = new RectangleF (labelXCoordStart, yCoordStart,newSize.Width, newSize.Height);
			ContentView.AddSubview (label);
			labelXCoordStart += newSize.Width + space;
		}
	}
}
