// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGHistoryTableCell : UITableViewCell
	{
		public BGHistoryTableCell (IntPtr handle) : base (handle)
		{

		}

		public void SetUp(string name, string count)
		{
			var attr = new NSAttributedString ("", UIFont.FromName (BGAppearanceConstants.FontName, 17), UIColor.Black);
			this.name.AttributedText = attr;
			this.count.AttributedText = attr;
			this.name.Text = name;
			this.count.Text = count;
		}
	}
}
