// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGSignaturesCell : UITableViewCell
	{
		public BGSignaturesCell (IntPtr handle) : base (handle)
		{
			TintColor = BGAppearanceConstants.TealGreen;
		}

		public void SetUp(string name)
		{
			this.name.AttributedText = new NSAttributedString (name, UIFont.FromName (BGAppearanceConstants.MediumFontName, 15), BGAppearanceConstants.DarkBrown);
		}
	}
}
