// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGStatsTableCell : UITableViewCell
	{
		public BGStatsTableCell (IntPtr handle) : base (handle)
		{
		}

		public void SetKeyValue(string key, string value)
		{
			this.key.Text = key;
			this.value.Text = value;
		}
	}
}
