// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Dialog.Utilities;

namespace BlahguaMobile.IOS
{
	public partial class BGBlahBadgeCell : UITableViewCell
	{
		public BGBlahBadgeCell (IntPtr handle) : base (handle)
		{
		}

		public void SetUp(string badgeName, string badgeImageUrl)
		{
			verifiedLabel.AttributedText = new NSAttributedString (
				"verified", 
				UIFont.FromName (BGAppearanceConstants.BoldFontName, 10), 
				UIColor.Black
			);
			Uri uri = null;
			if (Uri.TryCreate (badgeImageUrl, UriKind.RelativeOrAbsolute, out uri))
				badgeImage.Image = ImageLoader.DefaultRequestImage (uri, new ImageUpdateDelegate (badgeImage));
			else
				badgeImage.Image = UIImage.FromFile ("badges.png");

			this.badgeName.AttributedText = new NSAttributedString (
				badgeName, 
				UIFont.FromName (BGAppearanceConstants.BoldFontName, 10), 
				UIColor.Black
			);
		}
	}
}
