// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Drawing;

using BlahguaMobile.BlahguaCore;

using MonoTouch.Foundation;
using MonoTouch.Dialog.Utilities;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGRollViewCell : UICollectionViewCell, IImageUpdated
	{
		private InboxBlah blah;
		private UIImageView imageView;
		private UILabel label;
		private NSIndexPath path;

		public InboxBlah Blah 
		{
			get
			{
				return blah;
			}
		}

		public BGRollViewCell (IntPtr handle) : base (handle)
		{
			imageView = new UIImageView (new RectangleF (new PointF (0, 0), ContentView.Frame.Size));
			imageView.Hidden = false;
			ContentView.Add (imageView);
			label = new UILabel(new RectangleF(new PointF(8, 7), new SizeF( ContentView.Frame.Size.Width - 24.0f, ContentView.Frame.Size.Height - 33.0f)));
			label.Lines = 6;
			//	UIFont font = reusableId == BGBlahCellSizesConstants.TinyReusableId ? 
			//		UIFont.FromName (BGAppearanceConstants.FontName, 7.0f) : UIFont.FromName (BGAppearanceConstants.FontName, 14.0f);
			//	label.AttributedText = new NSAttributedString (inboxBlah.T, font, UIColor.Black);
			label.Hidden = false;
			ContentView.Add (label);
		}

		public void SetCellProperties(InboxBlah blah, string reusableId, SizeF size, NSIndexPath path)
		{
			this.blah = blah;
			if(!String.IsNullOrEmpty(blah.ImageURL))
			{
				imageView.Frame = new RectangleF (new PointF (0, 0), size);
				imageView.Image = ImageLoader.DefaultRequestImage (new Uri(blah.ImageURL), new ImageUpdateDelegate(imageView));
				imageView.Hidden = false;
			}
			else
			{
				imageView.Hidden = true;
			}

			if(!String.IsNullOrEmpty(blah.T))
			{
				label.Frame = new RectangleF(new PointF(8, 7), new SizeF(size.Width - 24.0f, size.Height - 33.0f));
				UIFont font = reusableId == BGBlahCellSizesConstants.TinyReusableId ? 
					UIFont.FromName (BGAppearanceConstants.FontName, 7.0f) : UIFont.FromName (BGAppearanceConstants.FontName, 14.0f);
				label.Hidden = false;
				label.AttributedText = new NSAttributedString (blah.T, font, UIColor.Black);
			}
			else
			{
				label.Hidden = true;
			}

			if ((!String.IsNullOrEmpty(blah.T)) && (!String.IsNullOrEmpty(blah.ImageURL)))
			{
				UIView.Animate(RandomInterval(path.Row), RandomInterval(path.Row), UIViewAnimationOptions.CurveEaseInOut | UIViewAnimationOptions.Autoreverse | UIViewAnimationOptions.Repeat | UIViewAnimationOptions.AllowUserInteraction, 
					() => 
					{
						label.Alpha = 1;
						imageView.Alpha = 0;
					}, 
					() => 
					{
						label.Alpha = 0;
						imageView.Alpha = .9f; 
					}
				);

			}
		}

		private int RandomInterval(int index)
		{
			int i = index % 5;
			switch(i)
			{
			case 0:
				return 2;
			case 1: 
				return 3;
			case 2: 
				return 5;
			case 3: 
				return 7;
			default:
			case 4: 
				return 11;
			}
		}

		#region IImageUpdated implementation

		public void UpdatedImage (Uri uri)
		{
			if(blah.ImageURL != null) 
			{
				var image = ImageLoader.DefaultRequestImage (new Uri (blah.ImageURL), this);
				imageView.Image = image == null ? new UIImage() : image;
			}
			LayoutSubviews ();
		}

		#endregion
	}
}
