// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGMenuTableHeaderView : UITableViewCell
	{
		public string Header
		{
			get
			{
				return headerLabel.Text;
			}
			set
			{
				if(headerLabel.Text != value)
				{
					headerLabel.AttributedText = new NSAttributedString(
						value, 
						UIFont.FromName(BGAppearanceConstants.BoldFontName, 17), 
						UIColor.White
					);
				}
			}
		}

		public BGMenuTableHeaderView (IntPtr handle) : base (handle)
		{
			ContentView.BackgroundColor = BGAppearanceConstants.DarkBrown;
		}
	}
}
