// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace BlahguaMobile.IOS
{
	public partial class BGMenuTableCellView : UITableViewCell
	{
		#region Fields

		#endregion

		#region Properties

		public string Text
		{
			get
			{
				return label.Text;
			}
			set
			{
				if(label.Text != value)
				{
					label.AttributedText = new NSAttributedString(
						value, 
						UIFont.FromName(BGAppearanceConstants.BoldFontName, 14), 
						UIColor.White
					);
				}
			}
		}

		#endregion

		public BGMenuTableCellView (IntPtr handle) : base (handle)
		{
			ContentView.BackgroundColor = BGAppearanceConstants.DarkBrown;
		}

		#region Methods

		public void SelectRow()
		{
			selectedImage.Hidden = false;
		}

		public void DeselectRow()
		{
			selectedImage.Hidden = true;
		}

		#endregion
	}
}
